# Generated by Django 2.1.8 on 2019-07-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adName', models.CharField(max_length=30, verbose_name='广告名称')),
                ('adImg', models.ImageField(upload_to='static/images/ad', verbose_name='广告图片')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerName', models.CharField(max_length=30, verbose_name='横幅名称')),
                ('bannerImg', models.ImageField(upload_to='static/images/banner', verbose_name='横幅图片')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='商品数量')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('description', models.CharField(max_length=100, verbose_name='商品描述')),
                ('img', models.ImageField(upload_to='static/images/upload', verbose_name='商品图片')),
                ('isActive', models.BooleanField(default=True, verbose_name='上架状态')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=30, verbose_name='商品类别名称')),
                ('typeImg', models.ImageField(upload_to='static/images/goodsType', verbose_name='商品类别图片')),
                ('isActive', models.BooleanField(default=True, verbose_name='上架状态')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('pwd', models.CharField(max_length=200, verbose_name='密码')),
                ('name', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=True, verbose_name='激活状态')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goodsType',
            field=models.ForeignKey(on_delete=True, to='index.GoodsType'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_id',
            field=models.ForeignKey(on_delete=True, to='index.Goods', verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.ForeignKey(on_delete=True, to='index.User', verbose_name='用户id'),
        ),
    ]
